services:
  database:
    container_name: crassus-database
    image: postgis/postgis:15-3.5-alpine
    ports:
      - "10321:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: crassus-api
    build:
      context: .
      dockerfile: Dockerfile


volumes:
  pgdata: