services:
  crassus-api:
    container_name: crassus-api
    image: ${DOCKER_USERNAME}/crassus-api:latest
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped
  database:
    container_name: ${POSTGRES_HOST}
    image: postgres:15.13-alpine3.21
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: