api.crassus.com.br:
  /login:
    - POST:
      - token
      - userId
      - nameId
    
  /races:
    /:userId:
      - GET:
        - id
        - raceName
        - distance
        - date
      - /:raceId:
        - GET:
          - name*
          - calories*
          - pace*
          - time*
          - elevation*
          - distance*
          - startTime*
          - georeference*
          - BPM


  /meals:
    /types:
      - GET:
        - typeId
        - typeName
    /:userId:
      - GET:
        - id
        - name
        - type
        - totalCalories
        - date
      - /:mealId:
        - GET:
          - name
          - calories
          - carbs
          - proteins
          - fats
          - time
          - foods:
            - name
            - quantity


  /foods:
    - GET:
      - id
      - name
      - calories/100g
      - carbs/100g
      - proteins/100g
      - fats/100g
